# Procfile (for Railway deployment)
web: node server.js

# railway.json (Railway configuration)
{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "nixpacks"
  },
  "deploy": {
    "numReplicas": 1,
    "sleepApplication": false,
    "restartPolicyType": "never"
  }
}
